name: CI (Pinned Geode SDK main)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: Win64
          - os: macos-latest
            target: Mac64
          - os: ubuntu-22.04
            target: Linux64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use pinned Geode SDK and build
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: main
          bindings: geode-sdk/bindings
          bindings-ref: 4.10.0
          targets: ${{ matrix.target }}